GOOGLE_API_KEY= "AIzaSyDVH0lCJpBtmCNLdAtyCoIzX_W0IkinwHY"
NCBI_API_KEY= "7485c4463a62e544c871685bdaa397f56f08"
UMLS_API_KEY="1de6e1ba-d9d6-46b7-aa6f-12a5f2ab5359"
EMBASE_API_KEY="a48d9ca96cb33d639dfe997c27e88e16"
EMBASE_BASE_URL="https://api.elsevier.com/content/search/index:embase"